name: SkyPvP
version: ${project.version}
author: PrimeAPI
main: de.primeapi.primeplugins.skypvp.SkyPvP
softdepend:
  - PrimeCore
commands:
  skypvp:
  fly:
  workbench:
    aliases:
      - wb
  gamemode:
    aliases:
      - gm
  warp:
  spawn:
  plotworld:
  npc: