name: SkyPvP
version: ${project.version}
author: PrimeAPI
main: de.primeapi.primeplugins.skypvp.SkyPvP
softdepend:
  - PrimeCore
load: POSTWORLD
commands:
  skypvp:
  fly:
  workbench:
    aliases:
      - wb
  gamemode:
    aliases:
      - gm
  teleport:
    aliases:
      - tp
  tphere:
  heal:
  feed:
  edititem:
  enderchest:
    aliases:
      - ec
  warp:
  spawn:
  plotworld:
  npc:
  region:
  build:
  stats:
  kit:
  vanish:
    aliases:
      - v
  head:
    aliases:
      - kopf
  giveitem:
  storage:
  shop:
